# Generated by Django 4.0.6 on 2022-09-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price']},
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='quanlity',
            new_name='quantity',
        ),
    ]
