# Generated by Django 4.0.6 on 2022-09-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quanlity',
            new_name='stock_quantity',
        ),
    ]
