# Generated by Django 4.0.6 on 2022-07-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_place_restaurant'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='place',
            table='Place',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='Restaurant',
        ),
    ]
