# Generated by Django 4.0.6 on 2022-07-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='myapp.publication'),
        ),
    ]
