# Generated by Django 4.0.6 on 2022-07-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_article_publications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publication',
            table='Publication',
        ),
    ]
